<?php

/**
 * Created by PhpStorm.
 * User: apersinger
 * Date: 5/17/2017
 * Time: 8:39 AM
 */

require 'MonthData.php';

class MonthDataEmployeeView Extends MonthData
{
    var $empName;

    /***
     * MonthDataEmployeeView constructor.
     * @param $oid - this is the mongo generated ID for month data
     * @param $empId
     * @param $empEmail
     * @param $date
     * @param $status
     * @param $blogTopic
     * @param string $empName
     *
     * Use OID for updating month data
     */
    function __construct($oid, $empId, $empEmail, $date, $status, $blogTopic, $empName = "")
    {
        parent::__construct($oid, $empId, $empEmail, $date, $blogTopic, $status);
        $this->empName = $empName;
    }

    function GetEmployeeName() {
        return $this->empName;
    }
    function GetMonthDataEmployeeId()
    {
        return parent::GetMonthDataEmployeeId(); // TODO: Change the autogenerated stub
    }

    function SetEmployeeName($val) {
        $this->empName = $val;
    }
}